server:
  http_listen_port: 3200

distributor:
  receivers:
    otlp:
      protocols:
        grpc:
        http:
    jaeger:
      protocols:
        grpc:
        thrift_binary:
        thrift_compact:
        thrift_http:
    zipkin:

compactor:
  ring:
    kvstore:
  compaction:
    compaction_window: 1h

metrics_generator:

storage:
  trace:
    backend: local
    local:
      path: /tmp/tempo/blocks

overrides:
