global:
  scrape_interval: 15s
  external_labels:
    monitor: "codelab-monitor"

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["env_alertmanager:9093"]

rule_files:
  - "/rules/*.yml"

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 5s
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "node"
    scrape_interval: 5s
    static_configs:
      - targets: ["env_node-exporter:9100"]

  - job_name: "traefik"
    scrape_interval: 5s
    static_configs:
      - targets: ["env_traefik:8082"]
