version: "3.9"
services:
  registry:
    image: registry:latest
    networks:
      - sicky-net
    ports:
      - 5000:5000
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 2s
      restart_policy:
        condition: on-failure

networks:
  sicky-net:
    external: true
