version: "3.9"
services:
  #Nats
  nats:
    image: nats:latest
    networks:
      - sicky-net
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
      update_config:
        parallelism: 1
        delay: 2s
      restart_policy:
        condition: on-failure

  # Redis
  redis:
    image: redis:alpine
    networks:
      - sicky-net
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
      update_config:
        parallelism: 1
        delay: 2s
      restart_policy:
        condition: on-failure

networks:
  sicky-net:
    external: true
